
let DATA=null, mapMode=localStorage.getItem('mapMode')||'google';
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const enc=s=>encodeURIComponent(s);
function euro(n){return new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(n||0)}
function googleDir(stops){return 'https://www.google.com/maps/dir/'+stops.map(enc).join('/')}
function googleEmbed(stops){return 'https://www.google.com/maps?output=embed&saddr='+enc(stops[0]||'Dublin')+'&daddr='+enc((stops.slice(1).join(' to '))||stops[0]||'Dublin')}
function appleDir(stops){let a=stops[0]||'', b=stops[stops.length-1]||a; return 'https://maps.apple.com/?saddr='+enc(a)+'&daddr='+enc(b)+'&dirflg=d'}
function todayIndex(){const now=new Date(); const ds=DATA.days.map(d=>new Date(d.date+'T12:00:00')); let idx=ds.findIndex(d=> now.toDateString()===d.toDateString()); return idx>=0?idx:0}
function weatherCode(c){const m={0:'☀️ Klar',1:'🌤 Überwiegend klar',2:'⛅ Teilweise bewölkt',3:'☁️ Bewölkt',45:'🌫 Nebel',48:'🌫 Reifnebel',51:'🌦 Niesel leicht',53:'🌦 Niesel',55:'🌧 Niesel stark',61:'🌧 Regen leicht',63:'🌧 Regen',65:'🌧 Regen stark',71:'🌨 Schnee leicht',73:'🌨 Schnee',75:'🌨 Schnee stark',80:'🌦 Schauer leicht',81:'🌧 Schauer',82:'⛈ Schauer stark',95:'⛈ Gewitter',96:'⛈ Gewitter/Hagel',99:'⛈ Starkes Gewitter'};return m[c]||'🌦 Wetterlage'}
async function loadWeather(day, el){try{const start=day.date,end=day.date;const [lat,lon]=day.coords;const url=`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max,wind_speed_10m_max,sunrise,sunset&timezone=Europe%2FDublin&start_date=${start}&end_date=${end}`; const r=await fetch(url); const j=await r.json(); if(!j.daily||!j.daily.time?.length){el.textContent='🌦 Wetter noch nicht verfügbar'; return} const d=j.daily; el.textContent=`${weatherCode(d.weather_code[0])} · ${Math.round(d.temperature_2m_min[0])}–${Math.round(d.temperature_2m_max[0])}°C · Regen ${d.precipitation_probability_max[0]??'–'}% · Wind ${Math.round(d.wind_speed_10m_max[0]||0)} km/h`; }catch(e){el.textContent='🌦 Wetter lädt später';}}
function renderDashboard(){const trip=new Date(DATA.days[0].date+'T00:00:00'); const diff=Math.ceil((trip-new Date())/86400000); $('#countdown').textContent=diff>0?diff+' Tage':'läuft/abgeschlossen'; $('#hotelTotal').textContent=euro(DATA.costs.hotels_total); const total=DATA.days.length; const done=JSON.parse(localStorage.getItem('doneDays')||'[]').length; $('#progressText').textContent=Math.round(done/total*100)+'%';}
function renderMap(){const all=DATA.route.map(r=>r.name.replace('/Abflug','')); const box=$('#mapBox'); if(mapMode==='google'){box.innerHTML=`<iframe loading="lazy" src="${googleEmbed(all)}"></iframe><div class="install">Google Maps Einbettung mit der Gesamtroute. Für zuverlässige Navigation bitte „groß öffnen“ nutzen.</div>`}else{box.innerHTML=`<div class="applebox"><h3>🍎 Apple Karten</h3><p>Apple Karten wird am zuverlässigsten als Direktlink geöffnet. Die App nutzt Start und Ziel der Gesamtetappe; die Tagesstopps stehen darunter in Reihenfolge.</p><p><a class="btn" href="${appleDir(all)}" target="_blank" rel="noopener">Gesamtroute in Apple Karten öffnen</a></p><p><a class="btn ghost" style="color:#173c30;background:#fff" href="${googleDir(all)}" target="_blank" rel="noopener">Alternativ Google Maps groß öffnen</a></p></div>`}
 $$('.segmented button').forEach(b=>b.classList.toggle('active',b.dataset.map===mapMode));
 $('#routeList').innerHTML=DATA.route.map(r=>`<div class="route-stop"><b>Tag ${r.day}: ${r.name}</b><span>${new Date(r.date).toLocaleDateString('de-DE',{weekday:'short',day:'2-digit',month:'2-digit'})}</span></div>`).join('')+`<div class="route-stop"><b>Komplette Route</b><span><a href="${googleDir(all)}" target="_blank">Google Maps öffnen</a></span></div>`;}
function renderToday(){const d=DATA.days[todayIndex()]; $('#today').innerHTML=`<div class="section-head"><h2>Heute / Schnellzugriff</h2><span class="badge">Tag ${d.day}</span></div><h3>${d.title}</h3><p>${d.hotel||''}</p><div class="chips"><span class="chip">🚗 ${d.distance_km||'–'} km</span><span class="chip">⏱ ${d.drive_time||'–'}</span><span class="chip" id="todayWeather">🌦 Wetter lädt</span></div><div class="links"><a href="#day-${d.day}" class="smallbtn">Tag öffnen</a><a href="${googleDir(d.route_stops)}" target="_blank" class="smallbtn">Google Maps</a><a href="${appleDir(d.route_stops)}" target="_blank" class="smallbtn">Apple Karten</a></div>`; loadWeather(d,$('#todayWeather'));}
function renderDays(){const done=new Set(JSON.parse(localStorage.getItem('doneDays')||'[]')); $('#days').innerHTML=DATA.days.map(d=>`<article class="day" id="day-${d.day}"><div class="day-head"><div class="day-meta"><span class="badge">Tag ${d.day}</span><span>${d.weekday}, ${new Date(d.date).toLocaleDateString('de-DE')}</span></div><h3>${d.title}</h3><div>${d.hotel||''}</div><div class="chips"><span class="chip">📍 ${d.overnight}</span><span class="chip">🚗 ${d.distance_km||'–'} km</span><span class="chip">⏱ ${d.drive_time||'–'}</span><span class="chip weather" data-day="${d.day}">🌦 Wetter lädt</span></div></div><div class="day-body"><div class="timeline">${d.segments.map(s=>`<div class="slot"><time>${s[0]}</time><div>${s[1]}</div></div>`).join('')}</div><div class="route-mini"><b>Tagesroute</b><ol>${d.route_stops.map(s=>`<li>${s}</li>`).join('')}</ol><div class="links"><a href="${googleDir(d.route_stops)}" target="_blank">🟢 Google Maps</a><a href="${appleDir(d.route_stops)}" target="_blank">🍎 Apple Karten</a><button class="smallbtn copy" data-stops="${d.route_stops.join(' → ').replace(/"/g,'&quot;')}">Stopps kopieren</button></div></div><div class="links">${(d.wiki||[]).map(w=>`<a target="_blank" href="${w.url}">📖 ${w.name}</a>`).join('')}</div>${d.day===6?renderRing():''}<label style="display:block;margin-top:14px"><input type="checkbox" class="done" data-day="${d.day}" ${done.has(d.day)?'checked':''}> Tag erledigt/markiert</label><textarea data-note="${d.day}" placeholder="Eigene Notizen zu Tag ${d.day}" style="width:100%;margin-top:12px;border:1px solid #ddd;border-radius:14px;padding:12px;min-height:82px">${localStorage.getItem('note-'+d.day)||''}</textarea></div></article>`).join('');
 $$('.day-head').forEach(h=>h.onclick=()=>h.parentElement.classList.toggle('open')); $$('.weather').forEach(el=>loadWeather(DATA.days.find(d=>d.day==el.dataset.day),el)); $$('.done').forEach(c=>c.onchange=()=>{let a=new Set(JSON.parse(localStorage.getItem('doneDays')||'[]')); let n=+c.dataset.day; c.checked?a.add(n):a.delete(n); localStorage.setItem('doneDays',JSON.stringify([...a]));renderDashboard();toast();}); $$('textarea[data-note]').forEach(t=>t.oninput=()=>{localStorage.setItem('note-'+t.dataset.note,t.value);}); $$('.copy').forEach(b=>b.onclick=()=>navigator.clipboard.writeText(b.dataset.stops).then(toast));}
function renderRing(){return `<div class="ring"><b>Ring of Kerry Detailplan</b><table><thead><tr><th>Zeit</th><th>Stopp</th><th>Aufenthalt</th><th>Hinweis</th></tr></thead><tbody>${DATA.ring.map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td></tr>`).join('')}</tbody></table></div>`}
function renderCosts(){const c=DATA.costs; const persons=2; const total=c.hotels_total+c.listed_entries_total; $('#costs').innerHTML=`<div class="cost-kpis"><div class="kpi"><span>Bekannte Kosten</span><b>${euro(total)}</b></div><div class="kpi"><span>Pro Person</span><b>${euro(total/persons)}</b></div><div class="kpi"><span>Pro Tag</span><b>${euro(total/DATA.days.length)}</b></div></div><table class="cost-table"><thead><tr><th>Kategorie</th><th>Betrag</th><th>Hinweis</th></tr></thead><tbody><tr><td>Hotels</td><td>${euro(c.hotels_total)}</td><td>Aus Excel-Spalte Preis</td></tr><tr><td>Eintritte/Parken aus Notizen</td><td>${euro(c.listed_entries_total)}</td><td>Automatisch extrahiert, bitte gegen gebuchte Tickets prüfen</td></tr><tr><td>Flug</td><td contenteditable data-cost="flug">${localStorage.getItem('cost-flug')||''}</td><td>manuell ergänzen</td></tr><tr><td>Mietwagen</td><td contenteditable data-cost="mietwagen">${localStorage.getItem('cost-mietwagen')||''}</td><td>manuell ergänzen</td></tr><tr><td>Essen & Pubs</td><td contenteditable data-cost="essen">${localStorage.getItem('cost-essen')||''}</td><td>unterwegs ergänzen</td></tr></tbody></table><p class="install">Tipp: Werte in den leeren Feldern anklicken und überschreiben. Wird lokal im Browser gespeichert.</p>`; $$('[data-cost]').forEach(e=>e.oninput=()=>localStorage.setItem('cost-'+e.dataset.cost,e.textContent));}
function renderChecklists(){const cats={Packliste:['Reisepass/Personalausweis','Führerschein','Kreditkarte','Regenjacke','Adapter/USB-C','Powerbank','Medikamente','Sonnenbrille','Wanderschuhe'],Unterwegs:['Hoteladresse prüfen','Mietwagen tanken/laden','Tickets speichern','Restaurant reservieren','Fotos sichern','Kosten eintragen']}; $('#checklists').innerHTML='<div class="checkgrid">'+Object.entries(cats).map(([cat,items])=>`<div class="checkcard"><h3>${cat}</h3>${items.map(i=>{let id='chk-'+cat+'-'+i;return `<label><input type="checkbox" data-check="${id}" ${localStorage.getItem(id)==='1'?'checked':''}> ${i}</label>`}).join('')}</div>`).join('')+'</div><p class="install"><b>iPhone:</b> In Safari öffnen → Teilen → „Zum Home-Bildschirm“. Danach startet die Seite wie eine App.</p>'; $$('[data-check]').forEach(c=>c.onchange=()=>{localStorage.setItem(c.dataset.check,c.checked?'1':'0');toast();});}
function toast(){const t=$('#toast');t.style.display='block';setTimeout(()=>t.style.display='none',1200)}
async function init(){DATA=await fetch('reise-data.json').then(r=>r.json()).catch(()=>null); if(!DATA){document.body.innerHTML='<main><h1>Daten konnten nicht geladen werden</h1></main>';return} renderDashboard();renderMap();renderToday();renderDays();renderCosts();renderChecklists(); $$('.segmented button').forEach(b=>b.onclick=()=>{mapMode=b.dataset.map;localStorage.setItem('mapMode',mapMode);renderMap()}); if('serviceWorker' in navigator) navigator.serviceWorker.register('service-worker.js').catch(()=>{});}
init();
